# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haiwera Blog
email: 982220546@qq.com
description: > # this means to ignore newlines until "baseurl:"
    我心匪石，不可转也。我心匪席，不可卷也。威仪棣棣，不可选也。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haiwera.xyz" # the base hostname & protocol for your site
github_username:  Haiwera
rourl: http://121.40.217.151/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title.html
paginate: 10
paginate_path: "page:num"

kramdown:
      syntax_highlighter: rouge
gems:
    [jekyll-paginate]
